version: '3.8'
services:

  openeyeservicegateway:
    container_name: openeyeservicegateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://openeyeserviceregistry:8761/eureka/
      - eureka.client.enabled=true
      - eureka.host=OpenEyeServiceRegistry
      - eureka.instance.preferIpAddress=true

    depends_on:
      openeyeserviceregistry:
        condition: service_healthy
    networks:
      - springboot-net
    restart: on-failure
    

networks:
  springboot-net:
    driver: bridge
    external: true