eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost    
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
     
server:
  port: 8080
spring:
  application:
    name: ServiceGateWay
  cloud:
    gateway:
      routes:
      - id: ATTENDANCE-SERVICE
        predicates:
        - Path=/attendance/**
        uri: lb://ATTENDANCE-SERVICE
      - id: EMPLOYEE-SERVICE
        predicates:
        - Path=/employee/**
        uri: lb://EMPLOYEE-SERVICE
      - id: IMAGE-SERVICE
        predicates:
        - Path=/images/**
        uri: lb://IMAGE-SERVICE
